<?php

/**
 * Implements hook_services_resources().
 */
function services_test_resource_services_resources() {
  return array(
    'services_test' => array(
      'retrieve' => array(
        'callback' => '_services_test_resource_retrieve',
        'args' => array(
          array(
            'name' => 'arg1',
            'optional' => FALSE,
            'source' => array('path' => 0),
            'type' => 'int',
            'description' => 'Test argument 1.',
          ),
        ),
        'access callback' => '_services_test_resource_access',
        'access arguments' => array('view'),
        'access arguments append' => TRUE,
      ),
      'actions' => array(
        'action_retrieve' => array(
          'access callback' => '_services_test_resource_access',
          'access arguments' => array('view'),
          'access arguments append' => TRUE,
          'callback' => '_services_test_resource_action_retrieve',
          'args' => array(
            array(
              'name' => 'arg1',
              'optional' => FALSE,
              'source' => array('path' => 0),
              'type' => 'int',
              'description' => 'Test argument 1.',
            ),
          ),
        ),
      ),
      'targeted_actions' => array(
        'test' => array(
          'access callback' => '_services_test_resource_access',
          'access arguments' => array('view'),
          'access arguments append' => TRUE,
          'callback' => '_services_test_resource_targeted_action_test',
          'args' => array(
            array(
              'name' => 'arg1',
              'optional' => FALSE,
              'source' => array('path' => 0),
              'type' => 'int',
              'description' => 'Test argument 1.',
            ),
          ),
        ),
      ),
    ),
  );
}

/**
 * CRUD retrieve callback.
 */
function _services_test_resource_retrieve($arg1) {
  return 'CRUD Retrieve ' . $arg1;
}

/**
 * Action retrieve callback.
 */
function _services_test_resource_action_retrieve($arg1) {
  return 'Action retrieve' . $arg1;
}


/**
 * Targeted Action test callback.
 */
function _services_test_resource_targeted_action_test($arg1) {
  return 'Targeted Action test' . $arg1;
}
/**
 * Access callback.
 */
function _services_test_resource_access($op) {
  return TRUE;
}
