<?php

/**
 * @file
 * Translation definitions for builtin data.
 */

function gmap_marker_labels_potx() {
  $marker_labels = array(
    0 => t('Small Red'),
    1 => t('Small Bright red'),
    2 => t('Small Orange'),
    3 => t('Small Pale Yellow'),
    4 => t('Small Yellow'),
    5 => t('Small Pale Green'),
    6 => t('Small Green'),
    7 => t('Small Dark Green'),
    8 => t('Small Flouro Green'),
    9 => t('Small Pale Blue'),
    10 => t('Small Light Blue'),
    11 => t('Small Blue'),
    12 => t('Small Dark Blue'),
    13 => t('Small Purple'),
    14 => t('Small Pink'),
    15 => t('Small Bright Pink'),
    16 => t('Small Brown'),
    17 => t('Small White'),
    18 => t('Small Light Gray'),
    19 => t('Small Gray'),
    20 => t('Small Black'),
    21 => t('Small Blue (Alternate)'),
    22 => t('Small Red (Alternate)'),
    23 => t('Big Blue'),
    24 => t('Big Red'),
    25 => t('X marks the spot'),
    26 => t('Sunday'),
    27 => t('Monday'),
    28 => t('Tuesday'),
    29 => t('Wednesday'),
    30 => t('Thursday'),
    31 => t('Friday'),
    32 => t('Saturday'),
    33 => t('Week'),
    34 => t('Blank'),
    35 => t('Cluster'),
    36 => t('Drupal'),
    37 => t('Line Vertex'),
    38 => t('Letters'),
    39 => t('Blue'),
    40 => t('Gray'),
    41 => t('Green'),
    42 => t('Light Blue'),
    43 => t('Orange'),
    44 => t('Pink'),
    45 => t('Purple'),
    46 => t('White'),
    47 => t('Yellow'),
    48 => t('Numbers'),
    49 => t('Route'),
  );
  return $marker_labels;
}
