<?php

// Uganda

function location_province_list_ug() {
  return array('KAL' => "Kalangala",
    'KMP' => "Kampala",
    'KAY' => "Kayunga",
    'KIB' => "Kiboga",
    'LUW' => "Luwero",
    'MAS' => "Masaka",
    'MPI' => "Mpigi",
    'MUB' => "Mubende",
    'MUK' => "Mukono",
    'NKS' => "Nakasongola",
    'RAK' => "Rakai",
    'SEM' => "Sembabule",
    'WAK' => "Wakiso",
    'BUG' => "Bugiri",
    'BUS' => "Busia",
    'IGA' => "Iganga",
    'JIN' => "Jinja",
    'KAB' => "Kaberamaido",
    'KML' => "Kamuli",
    'KPC' => "Kapchorwa",
    'KTK' => "Katakwi",
    'KUM' => "Kumi",
    'MAY' => "Mayuge",
    'MBA' => "Mbale",
    'PAL' => "Pallisa",
    'SIR' => "Sironko",
    'SOR' => "Soroti",
    'TOR' => "Tororo",
    'ADJ' => "Adjumani",
    'APC' => "Apac",
    'ARU' => "Arua",
    'GUL' => "Gulu",
    'KIT' => "Kitgum",
    'KOT' => "Kotido",
    'LIR' => "Lira",
    'MRT' => "Moroto",
    'MOY' => "Moyo",
    'NAK' => "Nakapiripirit",
    'NEB' => "Nebbi",
    'PAD' => "Pader",
    'YUM' => "Yumbe",
    'BUN' => "Bundibugyo",
    'BSH' => "Bushenyi",
    'HOI' => "Hoima",
    'KBL' => "Kabale",
    'KAR' => "Kabarole",
    'KAM' => "Kamwenge",
    'KAN' => "Kanungu",
    'KAS' => "Kasese",
    'KBA' => "Kibaale",
    'KIS' => "Kisoro",
    'KYE' => "Kyenjojo",
    'MSN' => "Masindi",
    'MBR' => "Mbarara",
    'NTU' => "Ntungamo",
    'RUK' => "Rukungiri");
}

/**
 * Returns minimum and maximum latitude and longitude needed to create a bounding box.
 */
function location_bounds_ug() {
  return array(
    'minlng' => 29.5619,
    'minlat' => -1.501367,
    'maxlng' => 35.02905,
    'maxlat' => 4.201733,
  );
}
